---
title: "Batting Performance of `r params$player`"
date: "today"
format: 
  html :
    theme: [simple, custom.scss]

highlight-style: dracula
execute: 
  freeze: auto
params:
  player: "Babar Azam"
---

```{r}
#| include: false
#| warning: false
#| message: false
library(cricketdata)
library(tidyverse)
library(ggtext)
player_id<-find_player_id(params$player)$ID
df<-fetch_player_data(player_id, "ODI") %>%
  mutate(NotOut = (Dismissal == "not out"))
```

We have data about `r nrow(params$player)` players. Performance of `r params$player` is shown below:

## ODI match scores by `r params$player`

```{r}
#| echo: false
#| warning: false
#| message: false
df<-fetch_player_data(player_id, "ODI") %>%
  mutate(NotOut = (Dismissal == "not out"))

AAave <- df %>%
  filter(!is.na(Runs)) %>%
  summarise(Average = sum(Runs) / (n() - sum(NotOut))) %>%
  pull(Average)

AAave <- df %>%
  filter(!is.na(Runs)) %>%
  filter(Date != "2022-12-26") %>%
  summarise(Average = sum(Runs) / (n() - sum(NotOut))) %>%
pull(Average)

library(ggthemes)
names(AAave) <- paste("Average =", round(AAave, 2))
AAave
title_text<-paste0(' Batting Performance `r params$player`')
# Plot ODI scores
 ggplot(df) +
  geom_hline(aes(yintercept = AAave), col="gray") +
  geom_point(aes(x = Date, y = Runs, col = NotOut))  +
  scale_y_continuous(sec.axis = sec_axis(~., breaks = AAave))+theme(legend.position = "none") +labs(title=' Batting Performance  in ODI') +theme_fivethirtyeight()+theme()
```

