---
title: "Data Analysis Workshop for PIE"
author: "[Zahid Asghar](https://zahedasghar.netlify.app)"
date: last-modified
date-format: "DD-MM-YYYY"
title-block-banner: "#27455C"
format: 
  html:
    embed-resources: true
    smooth-scroll: true
    theme: theme.scss
    fontcolor: black
    toc: true
    toc-location: left
    toc-title: Summary
    toc-depth: 3
css: logo1.css
execute: 
  warning: false
  freeze: auto
editor: 
  markdown: 
    wrap: 72
---

## Objectives

-   Delineate variables among various types, like nominal, ordinal and
    interval.

-   Importance of research question and research design for data
    analysis.

-   Understand important elements of data, summarising, visualization
    and tabulating data as per best practices

-   Correlation and Regression, Linear and Nonlinear regressions

-   Forecasting education needs: enrolment, infrastructure, human capita
    and other requirements

-   Becoming familiar with use of R (without downloading and with zero
    coding experience)

-   All slides, data , data codes and related stuff will be handed over
    to reproduce all training material and prepare reports whenever
    required after the training.

## Main Topics

### Defining and Measuring Concepts

conceptual definition, operational definition, unit of analysis,
ecological fallacy, (measurement) reliability, (measurement) validity,
(systematic, random) measurement error, Hawthorne effect, test-restest
method, (face, construct) validity.

### Measuring and Describing Variables with Real Data

constant/variable, nominal/ordinal/interval variable, dummy variable,
Likert item, when can you treat an ordinal variable as
interval/continuous?, mode/median/mean.

### Hypotheses and Comparisons

(independent, dependent) variable, (positive, negative, zero,
curvilinear) relationship, cross-tabulation, mean comparison

### Correlation and Linear Regression

correlation, scatterplot, Pearson's r, multicollinearity, (multiple)
regression, regression coefficient, standard error, prediction error,
"ordinary least squares", partial effects, interactive effects.

### Forecasting

Components of Time Series, Decomposition of Time Series, ARMA, ARIMA,
SARMA and other statistical models

## Daywise detail

+----------------+------------------------+------+------+------+
| Days           | Title                  | To   | Rea  |      |
|                |                        | pics | ding |      |
|                |                        | to   | mate |      |
|                |                        | be   | rial |      |
|                |                        | cov  |      |      |
|                |                        | ered |      |      |
+----------------+------------------------+------+------+------+
| 1 (Monday)     | Introduction to        | Intr |      |      |
|                | software               | oduc |      |      |
|                |                        | tion |      |      |
|                |                        | to   |      |      |
|                |                        | R,   |      |      |
|                |                        | RStu |      |      |
|                |                        | dio, |      |      |
|                |                        | P    |      |      |
|                |                        | OSIT |      |      |
|                |                        | C    |      |      |
|                |                        | loud |      |      |
|                |                        | ,    |      |      |
|                |                        | git  |      |      |
|                |                        | uhub |      |      |
+----------------+------------------------+------+------+------+
| 2 (Wedn esday) | Data Vocabulary,       |      |      |      |
|                | taxonomy (nominal,     |      |      |      |
|                | categorical, discrete, |      |      |      |
|                | continuous), cleaning  |      |      |      |
|                | and data wrangling     |      |      |      |
+----------------+------------------------+------+------+------+
|                | Reading/writing        | In   | c    |      |
|                | STATA/SPSS/csv/xlsx    | cl   | onti |      |
|                | webAPI data in R       | ass- | nued |      |
|                |                        | labs |      |      |
+----------------+------------------------+------+------+------+
| 3 (Monday)     | Data Visualization     | bar, | gr   |      |
|                | (when to make which    | scat | ap   |      |
|                | graph )                | ter, | hics |      |
|                |                        | line | for  |      |
|                |                        | and  | c    |      |
|                |                        | hi   | ateg |      |
|                |                        | stog | or   |      |
|                |                        | rams | ical |      |
|                |                        | with | and  |      |
|                |                        | edu  | cont |      |
|                |                        | cati | in   |      |
|                |                        | onal | uous |      |
|                |                        | case | data |      |
|                |                        | s    | u    |      |
|                |                        | tudy | sing |      |
|                |                        | data | R,   |      |
|                |                        | in   |      |      |
|                |                        | ggp  |      |      |
|                |                        | lot2 |      |      |
+----------------+------------------------+------+------+------+
| 3              | Lab on having data     | In-c | Appl |      |
|                | visuali zation         | lass | icat |      |
|                |                        | lab  | ions |      |
+----------------+------------------------+------+------+------+
| 4 (Wednesday)  | Data Tables, Measure   | Lear | Ta   |      |
|                | of central tendency,   | ning | bles |      |
|                | dispersion             | Data | from |      |
|                |                        | Ta   | var  |      |
|                |                        | bles | ious |      |
|                |                        | with | PIE  |      |
|                |                        | R as | r    |      |
|                |                        | pub  | esou |      |
|                |                        | li   | rces |      |
|                |                        | shed | and  |      |
|                |                        | in   | rep  |      |
|                |                        | w    | rodu |      |
|                |                        | orld | cing |      |
|                |                        | l    | ta   |      |
|                |                        | ea   | bles |      |
|                |                        | ding | like |      |
|                |                        | out  | 538, |      |
|                |                        | lets | NYT, |      |
|                |                        |      | WSJ, |      |
|                |                        |      | F    |      |
|                |                        |      | T... |      |
+----------------+------------------------+------+------+------+
| 4              | -   \*Lab\*\*          | In   |      |      |
|                |                        | c    |      |      |
|                |                        | lass |      |      |
|                |                        | lab  |      |      |
+----------------+------------------------+------+------+------+
| 5 (M onday)    | -   \*Exploratory Data | Data | data |      |
|                |     An alysis in R in  | Exp  | xray |      |
|                |     min utes\*\*       | lora | in R |      |
|                |                        | tion |      |      |
|                |                        | not  |      |      |
|                |                        | in   |      |      |
|                |                        | mo   |      |      |
|                |                        | nths |      |      |
|                |                        | /w   |      |      |
|                |                        | eeks |      |      |
|                |                        | but  |      |      |
|                |                        | in   |      |      |
|                |                        | min  |      |      |
|                |                        | utes |      |      |
+----------------+------------------------+------+------+------+
| 5 (Wedn esday) | Exploratory Data       | Lab  |      |      |
|                | Analysis in R          |      |      |      |
+----------------+------------------------+------+------+------+
| 6              | Regression             | How  |      |      |
|                | /Econometric Model     | to   |      |      |
|                | Results                | have |      |      |
|                |                        | res  |      |      |
|                |                        | ults |      |      |
|                |                        | of   |      |      |
|                |                        | var  |      |      |
|                |                        | ious |      |      |
|                |                        | mo   |      |      |
|                |                        | dels |      |      |
|                |                        | like |      |      |
|                |                        | t    |      |      |
|                |                        | hose |      |      |
|                |                        | of   |      |      |
|                |                        | lea  |      |      |
|                |                        | ding |      |      |
|                |                        | jour |      |      |
|                |                        | nals |      |      |
+----------------+------------------------+------+------+------+
| 6              | Lab                    |      |      |      |
+----------------+------------------------+------+------+------+
| 7 (M onday)    | Time Series , Sm       | -    |      |      |
|                | oothin gExpon ential   |    E |      |      |
|                | Smo othing             | xplo |      |      |
|                |                        | ring |      |      |
|                |                        |      |      |      |
|                |                        |      |      |      |
|                |                        |  and |      |      |
|                |                        |      |      |      |
|                |                        |      |      |      |
|                |                        |  vis |      |      |
|                |                        | uali |      |      |
|                |                        | zing |      |      |
|                |                        |      |      |      |
|                |                        |      |      |      |
|                |                        | time |      |      |
|                |                        |      |      |      |
|                |                        | se   |      |      |
|                |                        | ries |      |      |
|                |                        |      |      |      |
|                |                        | -    |      |      |
|                |                        |   Si |      |      |
|                |                        | mple |      |      |
|                |                        |      |      |      |
|                |                        |      |      |      |
|                |                        |    b |      |      |
|                |                        | ench |      |      |
|                |                        | mark |      |      |
|                |                        |      |      |      |
|                |                        |  met |      |      |
|                |                        | hods |      |      |
|                |                        |      |      |      |
|                |                        |      |      |      |
|                |                        |  for |      |      |
|                |                        |      |      |      |
|                |                        |      |      |      |
|                |                        |  for |      |      |
|                |                        | ecas |      |      |
|                |                        | ting |      |      |
|                |                        |      |      |      |
|                |                        | -    |      |      |
|                |                        |    D |      |      |
|                |                        | ecom |      |      |
|                |                        | posi |      |      |
|                |                        | tion |      |      |
|                |                        |      |      |      |
|                |                        |   of |      |      |
|                |                        |      |      |      |
|                |                        | Se   |      |      |
|                |                        | ries |      |      |
+----------------+------------------------+------+------+------+
| 8 (Wedn esday) | ARMA, ARIMA, SARIMA    |      |      |      |
|                | model, Forec asting    |      |      |      |
+----------------+------------------------+------+------+------+
| 9-10 (Opt      |                        | Revi |      |      |
| ional)         |                        | sion |      |      |
|                |                        | of   |      |      |
|                |                        | all  |      |      |
|                |                        | conc |      |      |
|                |                        | epts |      |      |
|                |                        | with |      |      |
|                |                        | pr   |      |      |
|                |                        | ac   |      |      |
|                |                        | tice |      |      |
+----------------+------------------------+------+------+------+

## New ways of having data and analyzing

### Analyzing Google Trends, Google News API, Media API

Discussion of various sources from where one can read all data directly
from web API. - Google trends - Google news API - Media API - UN votes
data from 1948-49 on 6 key issues directly from API till to-date
(Comparing Pakistan and India ) - Participants feedback for way forward
