---
title: "Data Analysis Workshop for PIE"
author: "[Zahid Asghar](https://zahedasghar.netlify.app)"
date: last-modified
date-format: "DD-MM-YYYY"
title-block-banner: "#27455C"
format: 
  html:
    embed-resources: true
    smooth-scroll: true
    theme: theme.scss
    fontcolor: black
    toc: true
    toc-location: left
    toc-title: Summary
    toc-depth: 3
css: logo1.css
execute: 
  warning: false
  freeze: auto
editor: 
  markdown: 
    wrap: 72
---

## Objectives

-   Delineate variables among various types, like nominal, ordinal and
    interval.

-   Importance of research question and research design for data
    analysis.

-   Understand important elements of data, summarising, visualization
    and tabulating data as per best practices

-   Correlation and Regression, Linear and Nonlinear regressions

-   Forecasting education needs: enrolment, infrastructure, human capita
    and other requirements

-   Becoming familiar with use of R (without downloading and with zero
    coding experience)

-   All slides, data , data codes and related stuff will be handed over
    to reproduce all training material and prepare reports whenever
    required after the training.

## Main Topics

### Defining and Measuring Concepts

conceptual definition, operational definition, unit of analysis,
ecological fallacy, (measurement) reliability, (measurement) validity,
(systematic, random) measurement error, Hawthorne effect, test-restest
method, (face, construct) validity.

### Measuring and Describing Variables with Real Data

constant/variable, nominal/ordinal/interval variable, dummy variable,
Likert item, when can you treat an ordinal variable as
interval/continuous?, mode/median/mean.

### Hypotheses and Comparisons

(independent, dependent) variable, (positive, negative, zero,
curvilinear) relationship, cross-tabulation, mean comparison

### Correlation and Linear Regression

correlation, scatterplot, Pearson's r, multicollinearity, (multiple)
regression, regression coefficient, standard error, prediction error,
"ordinary least squares", partial effects, interactive effects.

### Forecasting

Components of Time Series, Decomposition of Time Series, ARMA, ARIMA,
SARMA and other statistical models

## Daywise detail

+----------------+------------------------+------------+-------------------+------+
| Days           | Title                  | Topics to  | Reading material  |      |
|                |                        | be covered |                   |      |
+----------------+------------------------+------------+-------------------+------+
| 1 (Monday)     | Introduction to        | In         |                   |      |
|                | software               | troduction |                   |      |
|                |                        | to R,      |                   |      |
|                |                        | RStudio,   |                   |      |
|                |                        | POSIT      |                   |      |
|                |                        | Cloud ,    |                   |      |
|                |                        | gituhub    |                   |      |
+----------------+------------------------+------------+-------------------+------+
| 2 (Wedn esday) | Data Vocabulary,       |            |                   |      |
|                | taxonomy (nominal,     |            |                   |      |
|                | categorical, discrete, |            |                   |      |
|                | continuous), cleaning  |            |                   |      |
|                | and data wrangling     |            |                   |      |
+----------------+------------------------+------------+-------------------+------+
|                | Reading/writing        | In         | continued         |      |
|                | STATA/SPSS/csv/xlsx    | class-labs |                   |      |
|                | webAPI data in R       |            |                   |      |
+----------------+------------------------+------------+-------------------+------+
| 3 (Monday)     | Data Visualization     | bar,       | graphics for      |      |
|                | (when to make which    | scatter,   | categorical and   |      |
|                | graph )                | line and   | continuous data   |      |
|                |                        | histograms | using R,          |      |
|                |                        | with       |                   |      |
|                |                        | e          |                   |      |
|                |                        | ducational |                   |      |
|                |                        | case study |                   |      |
|                |                        | data in    |                   |      |
|                |                        | ggplot2    |                   |      |
+----------------+------------------------+------------+-------------------+------+
| 3              | Lab on having data     | In-class   | Applications      |      |
|                | visuali zation         | lab        |                   |      |
+----------------+------------------------+------------+-------------------+------+
| 4 (Wednesday)  | Data Tables, Measure   | Learning   | Tables from       |      |
|                | of central tendency,   | Data       | various PIE       |      |
|                | dispersion             | Tables     | resources and     |      |
|                |                        | with R as  | reproducing       |      |
|                |                        | pub lished | tables like 538,  |      |
|                |                        | in world l | NYT, WSJ, FT...   |      |
|                |                        | eading     |                   |      |
|                |                        | outlets    |                   |      |
+----------------+------------------------+------------+-------------------+------+
| 4              | -   \*Lab\*\*          | In class   |                   |      |
|                |                        | lab        |                   |      |
+----------------+------------------------+------------+-------------------+------+
| 5 (M onday)    | -   \*Exploratory Data | Data       | dataxray in R     |      |
|                |     An alysis in R in  | E          |                   |      |
|                |     min utes\*\*       | xploration |                   |      |
|                |                        | not in     |                   |      |
|                |                        | months     |                   |      |
|                |                        | /weeks but |                   |      |
|                |                        | in minutes |                   |      |
+----------------+------------------------+------------+-------------------+------+
| 5 (Wedn esday) | Exploratory Data       | Lab        |                   |      |
|                | Analysis in R          |            |                   |      |
+----------------+------------------------+------------+-------------------+------+
| 6              | Regression             | How to     |                   |      |
|                | /Econometric Model     | have       |                   |      |
|                | Results                | results of |                   |      |
|                |                        | various    |                   |      |
|                |                        | models     |                   |      |
|                |                        | like those |                   |      |
|                |                        | of leading |                   |      |
|                |                        | journals   |                   |      |
+----------------+------------------------+------------+-------------------+------+
| 6              | Lab                    |            |                   |      |
+----------------+------------------------+------------+-------------------+------+
| 7 (M onday)    | Time Series , Sm       | -          |                   |      |
|                | oothin gExpon ential   |  Exploring |                   |      |
|                | Smo othing             |     and    |                   |      |
|                |                        |     v      |                   |      |
|                |                        | isualizing |                   |      |
|                |                        |     time   |                   |      |
|                |                        |     series |                   |      |
|                |                        |            |                   |      |
|                |                        | -   Simple |                   |      |
|                |                        |            |                   |      |
|                |                        |  benchmark |                   |      |
|                |                        |            |                   |      |
|                |                        |    methods |                   |      |
|                |                        |     for    |                   |      |
|                |                        |     f      |                   |      |
|                |                        | orecasting |                   |      |
|                |                        |            |                   |      |
|                |                        | -   Dec    |                   |      |
|                |                        | omposition |                   |      |
|                |                        |     of     |                   |      |
|                |                        |     time   |                   |      |
|                |                        |     series |                   |      |
+----------------+------------------------+------------+-------------------+------+
| 8 (Wedn esday) | ARMA, ARIMA, SARIMA    |            |                   |      |
|                | model, Forec asting    |            |                   |      |
+----------------+------------------------+------------+-------------------+------+
| 9-10 (Opt      |                        | Revision   |                   |      |
| ional)         |                        | of all     |                   |      |
|                |                        | concepts   |                   |      |
|                |                        | with       |                   |      |
|                |                        | practice   |                   |      |
+----------------+------------------------+------------+-------------------+------+

## New ways of having data and analyzing

### Analyzing Google Trends, Google News API, Media API

Discussion of various sources from where one can read all data directly
from web API. - Google trends - Google news API - Media API - UN votes
data from 1948-49 on 6 key issues directly from API till to-date
(Comparing Pakistan and India ) - Participants feedback for way forward
